[2023-11-20T08:38:36.308+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-20T08:38:36.327+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-20T08:38:36.328+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:38:36.350+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-05 00:00:00+00:00
[2023-11-20T08:38:36.359+0000] {standard_task_runner.py:57} INFO - Started process 79 to run task
[2023-11-20T08:38:36.371+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-05T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpgzf9oaeb']
[2023-11-20T08:38:36.388+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask retrieve_data
[2023-11-20T08:38:36.480+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [running]> on host 74ca1234e792
[2023-11-20T08:38:36.584+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-05T00:00:00+00:00'
[2023-11-20T08:38:36.587+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 18, in retrieve_data
    aws_access_key_id=YOUR_ACCESS_KEY,
NameError: name 'YOUR_ACCESS_KEY' is not defined
[2023-11-20T08:38:36.598+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231105T000000, start_date=20231120T083836, end_date=20231120T083836
[2023-11-20T08:38:36.626+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task retrieve_data (name 'YOUR_ACCESS_KEY' is not defined; 79)
[2023-11-20T08:38:36.665+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T08:38:36.744+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:43:23.129+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-20T08:43:23.138+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-20T08:43:23.138+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:43:23.151+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-05 00:00:00+00:00
[2023-11-20T08:43:23.156+0000] {standard_task_runner.py:57} INFO - Started process 79 to run task
[2023-11-20T08:43:23.162+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-05T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp17p8u2eh']
[2023-11-20T08:43:23.166+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask retrieve_data
[2023-11-20T08:43:23.240+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [running]> on host c84b35a13244
[2023-11-20T08:43:23.339+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-05T00:00:00+00:00'
[2023-11-20T08:43:25.173+0000] {etl.py:60} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:43:25.174+0000] {etl.py:64} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:43:25.322+0000] {etl.py:71} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:43:25.714+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:43:25.720+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231105T000000, start_date=20231120T084323, end_date=20231120T084325
[2023-11-20T08:43:25.739+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:43:25.759+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:46:36.594+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-20T08:46:36.604+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-20T08:46:36.605+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:46:36.619+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-05 00:00:00+00:00
[2023-11-20T08:46:36.626+0000] {standard_task_runner.py:57} INFO - Started process 85 to run task
[2023-11-20T08:46:36.630+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-05T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmprtb4xjyu']
[2023-11-20T08:46:36.636+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask retrieve_data
[2023-11-20T08:46:36.740+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [running]> on host d26cbef9e8ab
[2023-11-20T08:46:36.839+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-05T00:00:00+00:00'
[2023-11-20T08:46:39.245+0000] {etl.py:62} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:46:39.248+0000] {etl.py:66} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:46:39.418+0000] {etl.py:73} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:46:41.750+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:46:41.802+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231105T000000, start_date=20231120T084636, end_date=20231120T084641
[2023-11-20T08:46:41.968+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:46:41.995+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:50:16.735+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-20T08:50:16.750+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-20T08:50:16.756+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:50:16.812+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-05 00:00:00+00:00
[2023-11-20T08:50:16.822+0000] {standard_task_runner.py:57} INFO - Started process 85 to run task
[2023-11-20T08:50:16.842+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-05T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpxecblamj']
[2023-11-20T08:50:16.848+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask retrieve_data
[2023-11-20T08:50:16.935+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-05T00:00:00+00:00 [running]> on host 3ef39241d6e6
[2023-11-20T08:50:17.050+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-05T00:00:00+00:00'
[2023-11-20T08:50:18.870+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:50:18.875+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:50:19.044+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:50:20.094+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:50:20.101+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231105T000000, start_date=20231120T085016, end_date=20231120T085020
[2023-11-20T08:50:20.139+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:50:20.218+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
